- name: Basic configuration of all cluster nodes
  hosts: all
  roles:
    - common
    - containerd
    - kube-deps

- name: Initializing control-plane
  hosts: control_plane
  roles:
    - control-plane
    - helm
    - storage
    - ingress
    - mysql
    - monitoring
    - zabbix

- name: Joining worker nodes
  hosts: workers
  roles:
    - worker
